name: Lint

# Запускать при push и pull_request в любые ветки (или конкретные, например: main, develop)
on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  # или ваша LTS‑версия

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        # Предположим, что в package.json есть скрипт "lint": "eslint 'src/**/*.{ts,js,tsx,jsx}'"
        run: npm run lint
